name: run python script

on:
  push:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      

        - name: setup python
          uses: actions/setup-python@v2,  actions/checkout@v2
          with:
            python-version: '3.11.2' # install the python version needed

        - name: install python packages
         
          run: |
            python -m pip install --upgrade pip


        - name: run py
          run: |
            python app.py
          
